### ISSUE TITLE
Ensure BIN folder exists

### ISSUE THREAD

**Issue by mpociot** [tighten/liftoff#8]
When running liftoff on a fresh mac installation, the `/usr/local/bin` directory does not yet exist. It gets created during the homebrew installation, but a fresh macOS only has an empty folder `/usr/local`.

https://github.com/tighten/liftoff/blob/main/liftoff.sh#L16

![image](https://user-images.githubusercontent.com/804684/97403146-295d4f80-18f4-11eb-8569-5784aa362853.png)

**Comment by mattstauffer** [comment]
Ahh, thanks @mpociot!
